import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Incluimos solo los specs que están escritos en estilo vitest
    // (describe/it/expect). El repo tiene 18 archivos .test.ts pre-existentes
    // con patrón `main().catch(...)` (scripts E2E ad-hoc) que NO son specs
    // vitest — vitest los rechaza con "No test suite found". Se irán
    // portando uno a uno; este include conservador evita romper CI mientras.
    include: [
      'src/audit/__tests__/audit_log.test.ts',
      'src/audit/__tests__/trust_ledger.test.ts',
      'src/audit/__tests__/audit_chain.test.ts',
      'src/backup/__tests__/**/*.test.ts',
      'src/security/__tests__/**/*.test.ts',
      'src/channels/__tests__/**/*.test.ts',
      'src/committee/__tests__/committee_evolutive.test.ts',
      'src/context/__tests__/**/*.test.ts',
      'src/coordinator/__tests__/**/*.test.ts',
      'src/memory/__tests__/memory_citations.test.ts',
      'src/memory/__tests__/providers.test.ts',
      'src/memory/__tests__/l1_cache.test.ts',
      'src/memory/__tests__/contradiction_filter.test.ts',
      'src/memory/__tests__/provenance.test.ts',
      'src/memory/__tests__/temporal_memory.test.ts',
      'src/memory/dreaming/__tests__/**/*.test.ts',
      'src/observability/__tests__/**/*.test.ts',
      'src/memory/embedding_providers/__tests__/**/*.test.ts',
      'src/persistence/__tests__/**/*.test.ts',
      'src/plugins/__tests__/**/*.test.ts',
      'src/providers/__tests__/**/*.test.ts',
      'src/reader/__tests__/deep_descent.test.ts',
      'src/reader/__tests__/multi_repo.test.ts',
      'src/runtime/__tests__/mission_scheduler.test.ts',
      'src/runtime/__tests__/remote_mode.test.ts',
      'src/runtime/__tests__/resource_governor.test.ts',
      'src/runtime/__tests__/escalation.test.ts',
      'src/selfdebug/__tests__/**/*.test.ts',
      'src/replay/__tests__/**/*.test.ts',
      'src/multiuser/__tests__/**/*.test.ts',
      'src/a2a/__tests__/**/*.test.ts',
      'src/benchmark/__tests__/**/*.test.ts',
      'src/gaia/__tests__/**/*.test.ts',
      'src/sandbox/__tests__/**/*.test.ts',
      'src/sandbox/browser_sandbox/__tests__/**/*.test.ts',
      'src/skills/__tests__/**/*.test.ts',
      'src/skills/auditor/__tests__/**/*.test.ts',
      'src/sentinel/__tests__/**/*.test.ts',
      'src/soul/__tests__/**/*.test.ts',
      'src/stt/__tests__/**/*.test.ts',
      'src/tools/__tests__/docker_backend.test.ts',
      'src/tools/__tests__/tool_pack_pure.test.ts',
      'src/tools/__tests__/voice_tools.test.ts',
      'src/tools/__tests__/spawn_agent.test.ts',
      'src/tools/__tests__/e2_e4_tools.test.ts',
      'src/tools/__tests__/tool_search.test.ts',
      'src/tools/__tests__/tool_activation.test.ts',
      'src/tools/__tests__/run_team.test.ts',
      'src/tui/__tests__/**/*.test.tsx',
      'src/web/__tests__/pwa.test.ts',
      'src/browser/__tests__/**/*.test.ts',
      'src/dispatch/__tests__/**/*.test.ts',
      'src/mcp/__tests__/**/*.test.ts',
      'src/lsp/__tests__/**/*.test.ts',
      'src/bench/__tests__/**/*.test.ts',
      'src/agents/__tests__/**/*.test.ts',
      'src/integrity/__tests__/**/*.test.ts',
      'src/kagemusha/__tests__/**/*.test.ts',
      'src/kagami/__tests__/**/*.test.ts',
      'src/chizu/__tests__/**/*.test.ts',
      'src/shugyo/__tests__/**/*.test.ts',
      'src/tenshu/__tests__/**/*.test.ts',
      'src/kangeiko/__tests__/**/*.test.ts',
      'src/shitsuji/__tests__/**/*.test.ts',
      'src/kaname/__tests__/**/*.test.ts',
      'src/egress/__tests__/**/*.test.ts',
      'src/__tests__/stress/**/*.test.ts',
    ],
    exclude: ['node_modules', 'dist', 'scratch', 'test_*.ts'],
    pool: 'forks',
    isolate: true,
    globals: false,
    testTimeout: 10_000,
  },
});
