// D.3 runner — ejecuta la mision piloto 3 veces consecutivas contra el mismo
// repo (execa) y verifica que el contrato pasa sin intervencion humana.
// Output: docs/D3_VALIDATION.md con el resumen + commits a audits/.

import * as fs from 'fs';
import * as path from 'path';
import { spawnSync } from 'child_process';
import { runAudit } from '../src/audit/runAudit.js';

const TARGET_URL = 'https://github.com/sindresorhus/execa';

async function main() {
  // Resolve a fixed SHA from the local clone we already have so the 3 runs are deterministic.
  const localExeca = 'C:\\Users\\angel\\Desktop\\test_repos\\execa';
  let pinnedSha: string | undefined;
  if (fs.existsSync(localExeca)) {
    const r = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: localExeca, encoding: 'utf-8' });
    if (r.status === 0) pinnedSha = (r.stdout || '').trim();
  }
  console.log(`[d3_run] target: ${TARGET_URL}`);
  console.log(`[d3_run] pinned SHA: ${pinnedSha ?? '(none — using HEAD at clone time)'}`);
  console.log('');

  const runs: { idx: number; ok: boolean; verdict: string; risk: string; durationMs: number; contractPass: boolean; reasons: string[]; mdPath: string }[] = [];

  for (let i = 1; i <= 3; i++) {
    console.log('═══════════════════════════════════════════════════════════════');
    console.log(`D.3 — RUN ${i}/3`);
    console.log('═══════════════════════════════════════════════════════════════');
    const r = await runAudit({ url: TARGET_URL, commit: pinnedSha });
    runs.push({
      idx: i,
      ok: r.ok,
      verdict: r.verdict,
      risk: r.overallRisk,
      durationMs: r.durationMs,
      contractPass: r.contractPass,
      reasons: r.contractReasons,
      mdPath: r.mdPath,
    });
    console.log('');
  }

  // Summary doc.
  const docPath = path.join(process.cwd(), 'docs', 'D3_VALIDATION.md');
  const ts = new Date().toISOString();
  const allPass = runs.every((r) => r.contractPass);
  const lines: string[] = [];
  lines.push('# D.3 — 3 ejecuciones consecutivas de la mision piloto');
  lines.push('');
  lines.push(`Fecha: ${ts}`);
  lines.push(`Target: \`${TARGET_URL}\``);
  if (pinnedSha) lines.push(`Pinned SHA: \`${pinnedSha}\``);
  lines.push('');
  lines.push(`Gate D.3: 3 ejecuciones consecutivas pasan el contrato sin intervencion humana.`);
  lines.push('');
  lines.push(`**Resultado**: ${allPass ? 'VERDE — gate cumplido' : 'ROJO — gate NO cumplido'}`);
  lines.push('');
  lines.push('| Run | Verdict | Risk | Duration | Contract | MD |');
  lines.push('|-----|---------|------|----------|----------|----|');
  for (const r of runs) {
    const cFlag = r.contractPass ? '✅ PASS' : '❌ FAIL';
    lines.push(`| ${r.idx} | ${r.verdict} | ${r.risk} | ${(r.durationMs / 1000).toFixed(1)}s | ${cFlag} | \`${path.relative(process.cwd(), r.mdPath)}\` |`);
  }
  lines.push('');
  for (const r of runs) {
    if (!r.contractPass) {
      lines.push(`### Run ${r.idx} — razones del fallo del contrato`);
      for (const reason of r.reasons) lines.push(`- ${reason}`);
      lines.push('');
    }
  }
  lines.push('---');
  lines.push('');
  lines.push('Generated by `scripts/d3_run.ts`. Re-run with `npx tsx scripts/d3_run.ts`.');
  fs.writeFileSync(docPath, lines.join('\n') + '\n');
  console.log(`[d3_run] summary written to ${docPath}`);

  process.exit(allPass ? 0 : 1);
}

main().catch((e) => { console.error('[d3_run] FATAL:', e); process.exit(2); });
