/**
 * Corpus sintético para validar el upgrade de embeddings.
 *
 * 10 categorías × 100 frases = 1000 entradas. Las frases dentro de cada
 * categoría comparten temática pero usan vocabulario variado (no son
 * templates triviales que un hash detectaría por coincidencia léxica).
 *
 * Para cada categoría se proveen 3 queries de paráfrasis: usan palabras
 * SEMÁNTICAMENTE cercanas pero LÉXICAMENTE distintas a las frases del
 * corpus. Un embedding semántico debe encontrar las frases correctas;
 * un hash bag-of-chars no.
 */

export interface CorpusEntry {
  text: string;
  category: string;
}

export interface CorpusQuery {
  query: string;
  category: string;
}

const CATEGORIES: Record<string, { phrases: string[]; queries: string[] }> = {
  programming: {
    phrases: [
      'El bucle for itera sobre el arreglo de números',
      'TypeScript añade tipos estáticos a JavaScript',
      'Rust previene memory bugs en tiempo de compilación',
      'Una función pura no muta su entorno',
      'Los closures capturan variables del scope exterior',
      'Async/await simplifica el manejo de promesas',
      'Git rebase reescribe la historia del repositorio',
      'El patrón Singleton garantiza una sola instancia',
      'Las interfaces definen contratos sin implementación',
      'El garbage collector libera memoria no referenciada',
      'Los hooks de React responden al lifecycle del componente',
      'La inversión de dependencias mejora el testing',
      'Las migraciones de base de datos son reversibles',
      'Un dataclass elimina boilerplate de getters y setters',
      'El polimorfismo permite tratar objetos de forma uniforme',
      'TDD escribe el test antes que la implementación',
      'Los generadores producen valores bajo demanda',
      'WebAssembly ejecuta código nativo en el navegador',
      'Los streams procesan datos sin cargar todo en memoria',
      'Una API REST expone recursos vía verbos HTTP',
      'GraphQL permite al cliente pedir exactamente lo que necesita',
      'Los webhooks son llamadas HTTP entrantes a tu servidor',
      'JWT codifica claims firmados criptográficamente',
      'CORS controla qué orígenes pueden llamar tu API',
      'El virtual DOM optimiza la actualización de la UI',
      'Una promise atómica resuelve una sola vez',
      'El throttle limita la frecuencia de llamadas',
      'Debounce espera silencio antes de ejecutar',
      'Las inmutabilidades simplifican el razonamiento concurrente',
      'Una palabra clave reservada no puede ser identificador',
      'El compilador linkea símbolos externos',
      'Una refactorización no cambia el comportamiento observable',
      'Los tests E2E cubren flujos completos de usuario',
      'Mocks aíslan la unidad bajo prueba',
      'Code coverage mide qué líneas ejecutan los tests',
      'CI/CD automatiza build y deployment',
      'Docker empaqueta dependencias junto al binario',
      'Kubernetes orquesta contenedores en un cluster',
      'Las service meshes manejan tráfico entre microservicios',
      'Una pull request propone cambios al main branch',
      'Code review captura bugs antes de mergear',
      'El semaphore limita acceso concurrente a un recurso',
      'Una race condition surge cuando el orden importa',
      'Deadlock: dos procesos esperan recursos mutuamente',
      'Big O describe cómo crece el coste con la entrada',
      'Quicksort tiene promedio O(n log n)',
      'Hash tables ofrecen acceso O(1) amortizado',
      'Los árboles balanceados mantienen profundidad logarítmica',
      'Grafos dirigidos modelan relaciones unidireccionales',
      'Dijkstra encuentra el camino más corto desde un origen',
      'BFS explora capa a capa, DFS por profundidad',
      'Una hash collision genera ambigüedad en el lookup',
      'El consenso distribuido usa quórum mayoritario',
      'Raft elige un líder mediante votación',
      'CAP teorema: consistencia, disponibilidad, partición',
      'Eventual consistency converge eventualmente al estado final',
      'Las particiones de Kafka paralelizan el throughput',
      'Redis sirve datos calientes con baja latencia',
      'PostgreSQL soporta transacciones ACID completas',
      'Los índices acelerent SELECT a costa de INSERT',
      'EXPLAIN revela el plan de ejecución del query',
      'B-trees son la estructura típica de los índices',
      'Vacuum recupera espacio de tuplas muertas',
      'WAL persiste cambios antes que en disco final',
      'Replicación maestro-esclavo escala lecturas',
      'Sharding particiona datos por una llave',
      'Las transacciones serializables previenen anomalías',
      'Read uncommitted permite phantom reads',
      'Optimistic locking compara versiones al commitar',
      'Pessimistic locking bloquea inmediatamente',
      'NoSQL trade-ea consistencia por escalabilidad',
      'Document stores guardan JSON anidado',
      'Time series databases optimizan inserción append-only',
      'Vector databases hacen búsqueda por similaridad',
      'Embeddings convierten texto a vectores densos',
      'Cosine similarity mide el ángulo entre vectores',
      'KNN encuentra los vecinos más cercanos',
      'HNSW indexa vectores para búsqueda aproximada',
      'Fine-tuning ajusta un modelo a un dominio específico',
      'Transfer learning reutiliza pesos pre-entrenados',
      'Backpropagation calcula gradientes hacia atrás',
      'Gradient descent minimiza la función de pérdida',
      'Overfitting memoriza el train set sin generalizar',
      'Regularización penaliza pesos grandes',
      'Dropout desactiva neuronas aleatoriamente durante training',
      'Batch normalization estabiliza el entrenamiento',
      'Attention pesa partes relevantes del input',
      'Transformers procesan secuencias en paralelo',
      'GPT genera texto token a token',
      'BERT codifica contexto bidireccionalmente',
      'Few-shot learning aprende de pocos ejemplos',
      'Chain of thought mejora razonamiento del LLM',
      'RAG combina retrieval con generación',
      'Function calling permite al LLM invocar tools',
      'Tool use estructura las llamadas externas',
      'Las allucinaciones producen contenido inventado',
      'Temperature controla la aleatoriedad del muestreo',
      'Top-p sampling considera el núcleo de probabilidad',
      'Beam search explora múltiples continuaciones',
      'KV cache acelera generación autoregresiva',
      'Prompt engineering refina la entrada al modelo',
      'System prompt establece el rol del asistente',
    ],
    queries: [
      'cómo aprender a programar de forma efectiva',
      'mejores prácticas de desarrollo de software',
      'qué framework usar para construir una aplicación web',
    ],
  },
  cocina: {
    phrases: [
      'Sofríe la cebolla hasta que esté translúcida',
      'La salsa debe reducirse a la mitad antes de servir',
      'Marinar la carne durante seis horas mejora el sabor',
      'El pan necesita reposar treinta minutos antes de hornear',
      'Una pizca de sal realza los sabores del dulce',
      'El aceite de oliva extra virgen es para crudo',
      'El roux blanco se cocina sin cambiar de color',
      'Las hierbas frescas se añaden al final de la cocción',
      'Un caldo bien clarificado debe ser transparente',
      'La masa madre fermenta de forma natural',
      'El bizcocho está listo cuando el palillo sale limpio',
      'Glasea las verduras con mantequilla y azúcar',
      'Flamear con coñac aporta complejidad aromática',
      'Reduce el vino tinto para concentrar sus taninos',
      'El brassage es la fase clave de la elaboración cervecera',
      'El kombucha fermenta con la madre SCOBY',
      'El kimchi necesita fermentar tres días a temperatura ambiente',
      'La masa de croissant lleva veintisiete capas de mantequilla',
      'El chocolate templado tiene brillo y crujido',
      'Una mayonesa rota se rescata añadiendo otra yema',
      'El umami viene de glutamatos naturales',
      'Las algas wakame se hidratan en minutos',
      'El dashi es la base de muchas sopas japonesas',
      'Un risotto cremoso requiere agitar constantemente',
      'El al dente se mide al morder la pasta',
      'La pasta fresca cuece en dos minutos',
      'Un buen brodo se hace a fuego mínimo durante horas',
      'El cardamomo verde aporta notas cítricas',
      'El cilantro fresco transforma una salsa cruda',
      'Las setas porcini secas se rehidratan en agua tibia',
      'El bacalao confitado a baja temperatura queda jugoso',
      'Sellar la carne a fuego alto crea costra de Maillard',
      'El sous-vide preserva la jugosidad de los pescados',
      'Un steak medio raro tiene centro rojo y tibio',
      'La grasa intramuscular hace tierna la carne',
      'Reposar la carne tras cocinar retiene los jugos',
      'El fondo oscuro se hace con huesos tostados',
      'La salsa española es uno de los cinco fondos clásicos',
      'Un consomé bien hecho concentra el sabor sin grasa',
      'El bisque clásico lleva crustáceos triturados',
      'Una vinagreta emulsiona tres partes aceite por una de vinagre',
      'El balsámico añejo se reduce hasta jarabe',
      'El aceite de trufa transforma una pasta sencilla',
      'El parmesano envejecido tiene cristales crujientes',
      'Una tortilla de patatas francesa es jugosa por dentro',
      'El gazpacho andaluz se sirve bien frío',
      'El salmorejo lleva pan y huevo cocido',
      'La paella valenciana lleva conejo y pollo',
      'Un sofrito catalán es la base de muchos guisos',
      'El alioli auténtico es solo ajo y aceite',
      'El mojo picón canario lleva pimentón y ajo',
      'El cochinillo se cocina entero hasta que la piel cruje',
      'El asado argentino respeta tiempos largos a brasa baja',
      'El ceviche peruano marina pescado en cítricos',
      'El pisco sour lleva clara de huevo batida',
      'La masa choux infla por el vapor interno',
      'Los profiteroles se rellenan tras enfriarse',
      'El crème caramel necesita baño maría',
      'Un soufflé colapsa si abres el horno antes de tiempo',
      'La tarta tatin se invierte tras hornear',
      'La galette des rois esconde una sorpresa',
      'Las macarons llevan almendra molida muy fina',
      'Un macaron correcto tiene pie liso y brillo',
      'El opera cake intercala capas de almendra y café',
      'Un fondant de chocolate sale con corazón fluido',
      'El cremoso de chocolate necesita gelificarse',
      'Los petit fours acompañan el café final',
      'Un canelé bordelés lleva corteza caramelizada',
      'La crema pastelera espesa con yemas y maicena',
      'El sabayón se monta al baño maría con vino dulce',
      'Una mousse aireada lleva claras montadas',
      'La nata para montar necesita estar muy fría',
      'El merengue italiano usa almíbar a punto de bola',
      'El merengue francés se monta en seco con azúcar',
      'Una espuma de sifón requiere cápsulas de N2O',
      'La esferificación crea perlas con membrana',
      'El nitrógeno líquido congela helados al instante',
      'La gastronomía molecular juega con texturas',
      'El umami quinto sabor activa receptores específicos',
      'El sake se sirve frío o templado según calidad',
      'El miso shiro es más suave que el aka',
      'El tofu sedoso se desmenuza con facilidad',
      'El tempeh fermenta granos de soja entera',
      'El seitán es proteína de gluten texturizado',
      'La quinoa se enjuaga para quitar las saponinas',
      'El amaranto explota como palomitas al tostarse',
      'El trigo sarraceno no contiene gluten',
      'La harina de garbanzo enriquece masas saladas',
      'Un hummus cremoso necesita tahini de calidad',
      'El baba ganoush ahuma berenjenas asadas',
      'El tabulé libanés lleva más perejil que cuscús',
      'El kebab vertical se corta en lonchas finas',
      'El falafel se fríe en bolas crujientes',
      'El curry verde tailandés lleva pasta de albahaca',
      'El laksa malayo combina coco y especias',
      'El pho vietnamita reposa caldo durante horas',
      'El ramen tonkotsu emulsiona la grasa de cerdo',
      'El gyoza se sella primero y luego se cuece al vapor',
      'El pad thai equilibra dulce, ácido y umami',
    ],
    queries: [
      'cómo preparar una receta sabrosa',
      'técnicas gastronómicas para platos elaborados',
      'qué ingredientes uso para una cena especial',
    ],
  },
  deportes: {
    phrases: [
      'El maratón olímpico mide 42 kilómetros y 195 metros',
      'Un tiro libre indirecto requiere dos toques antes del gol',
      'La pértiga moderna usa fibra de vidrio flexible',
      'Un home run sale del campo sobre la valla',
      'El triple en baloncesto vale más fuera de la línea de 6.75',
      'El penalti se patea desde once metros',
      'Un set de tenis acaba en seis juegos con diferencia de dos',
      'El golpe drive cruza el campo en diagonal',
      'Un putt corto requiere mucho control',
      'El swing de golf usa palanca de muñeca',
      'En boxeo, un cross cruza desde el lado dominante',
      'El uppercut sube desde abajo al mentón',
      'El jab abre la guardia del rival',
      'En judo, el ippon termina el combate al instante',
      'El koka era el punto técnico mínimo en judo',
      'El mawashi geri es una patada circular',
      'El karategi tiene cinturón de color graduado',
      'En esgrima, el florete puntúa solo con la punta',
      'El sable permite golpes con el filo',
      'La espada usa todo el cuerpo como blanco válido',
      'El esquí alpino combina velocidad y técnica',
      'El slalom giganto exige curvas amplias',
      'El descenso baja con poco viraje y máxima velocidad',
      'En patinaje artístico, un axel salto requiere giro y medio',
      'El triple lutz es uno de los saltos más difíciles',
      'En curling, el barrido controla la trayectoria de la piedra',
      'El biatlón mezcla esquí de fondo y tiro con rifle',
      'En remo, la cadencia ideal está cerca de 30 paladas por minuto',
      'El kayak K1 olímpico se navega individualmente',
      'En vela, el ceñido va contra el viento',
      'La empopada navega de bolina abierta',
      'En surf, el rip current arrastra a los nadadores',
      'Un cutback corta la onda en zigzag',
      'En ciclismo, el peloton agrupa a la mayoría de corredores',
      'El maillot amarillo identifica al líder del Tour',
      'El attaque sólido rompe el peloton en su mejor momento',
      'Un sprinter explosivo gana etapas llanas',
      'Un escalador puro brilla en los puertos de montaña',
      'En F1, el undercut consiste en parar antes que el rival',
      'El overcut alarga la parada para ganar aire libre',
      'Las gomas blandas dan más agarre pero duran menos',
      'En Le Mans, los relevos se cambian cada cuatro horas',
      'El rally cruza terrenos variados a alta velocidad',
      'El copiloto canta las notas anticipando curvas',
      'En motociclismo, el knee down marca el ángulo de inclinación',
      'Un wheelie despega la rueda delantera',
      'El stoppie levanta la rueda trasera al frenar',
      'En MMA, el guard cerrado controla al rival desde abajo',
      'Un takedown lleva la pelea al suelo',
      'El choke aéreo busca presión sobre las arterias',
      'En lucha grecorromana solo cuentan agarres por encima de la cintura',
      'El freestyle wrestling permite todo tipo de agarres',
      'En halterofilia, el clean and jerk combina dos fases',
      'El snatch lleva la barra del suelo al sobre la cabeza',
      'En crossfit, el WOD cambia cada día',
      'El AMRAP cuenta repeticiones en tiempo fijo',
      'El EMOM espacia esfuerzos por minuto',
      'En gimnasia artística, una D-score mide la dificultad',
      'La E-score evalúa la ejecución técnica',
      'Un doble carpado salto plancha lleva máxima dificultad',
      'En natación, el viraje croll usa flip turn',
      'El estilo mariposa exige ondulación corporal',
      'En polo acuático, el portero juega con guantes especiales',
      'El waterpolo permite una mano sobre la pelota',
      'En atletismo, el relevo 4x100 pasa el testigo dentro de zona',
      'El triple salto combina hop, step y jump',
      'La jabalina actual está rediseñada para volar menos',
      'El martillo gira sobre talones antes de soltar',
      'En halterofilia hay categorías por peso corporal',
      'El parkour fluye entre obstáculos urbanos',
      'El skate moderno mezcla street y vert',
      'Un kickflip rota la tabla sobre su eje longitudinal',
      'Un grind desliza el camión sobre el borde',
      'En BMX, el bunny hop levanta la bici sin rampa',
      'El tabletop estira la moto en el aire',
      'En snowboard, el switch invierte la postura habitual',
      'Un grab agarra la tabla durante el salto',
      'En esports, el APM mide acciones por minuto',
      'El meta cambia cada parche del juego',
      'Un patch grande puede invertir el ranking de personajes',
      'El K/D ratio mide bajas por muerte',
      'En LoL, la jungla limpia camps neutrales',
      'El support protege al ADC en la línea inferior',
      'En CS, el AWP es el rifle de precisión más caro',
      'Un eco-round limita el gasto del equipo',
      'El clutch gana una ronda contra varios enemigos',
      'En Starcraft, el build order define la apertura',
      'El cheese es una estrategia agresiva temprana',
      'En ajedrez, una apertura sólida controla el centro',
      'Un gambito sacrifica material por desarrollo',
      'La defensa siciliana es la respuesta más popular a 1.e4',
      'El final de peones requiere cálculo preciso',
      'Un zugzwang fuerza una jugada perjudicial',
      'El elo Elo mide la fuerza relativa de cada jugador',
      'En billar, el efecto desplaza la trayectoria de la bola',
      'Un masse curva la bola por giro extremo',
      'En dardos, el doble veinte es el objetivo principal',
      'Un checkout de 170 cierra una partida 501',
      'En bolos, el strike derriba todos los pinos',
      'Un spare derriba los pinos restantes en la segunda tirada',
      'En pesca deportiva, la mosca seca imita un insecto sobre el agua',
      'La pesca a fondo busca peces en columnas inferiores',
    ],
    queries: [
      'cómo entrenar para competiciones atléticas',
      'reglas básicas de un deporte de equipo',
      'qué disciplina deportiva combina varios elementos',
    ],
  },
  historia: {
    phrases: [
      'La caída de Constantinopla marcó el fin del Imperio Bizantino',
      'La Revolución Francesa derribó la monarquía Borbón',
      'La Gran Muralla protegía las dinastías chinas del norte',
      'Los romanos construían acueductos para llevar agua a las ciudades',
      'La conquista de América empezó tras 1492',
      'El Imperio Otomano duró seis siglos',
      'La Reforma protestante dividió al cristianismo occidental',
      'La Ilustración promovió la razón sobre el dogma',
      'La Revolución Industrial transformó el modelo económico',
      'Las trincheras dominaron el frente occidental en la Gran Guerra',
      'La Guerra Civil Española duró tres años',
      'La Guerra Fría enfrentó dos bloques sin combate directo',
      'La caída del Muro de Berlín simbolizó el fin del bloque soviético',
      'El Apolo 11 llevó a la humanidad a la Luna en 1969',
      'La Revolución Cubana instaló el régimen castrista',
      'La descolonización africana se aceleró tras la Segunda Guerra',
      'El Imperio Inca se extendía desde Ecuador hasta Chile',
      'Los aztecas fundaron Tenochtitlán sobre un lago',
      'Los mayas desarrollaron escritura jeroglífica compleja',
      'La civilización egipcia floreció en el valle del Nilo',
      'Las pirámides de Giza fueron tumbas faraónicas',
      'Tutankamón fue un faraón joven con tumba conservada',
      'Cleopatra fue la última faraona ptolemaica',
      'Julio César cruzó el Rubicón en 49 a.C.',
      'Augusto consolidó el Imperio Romano',
      'Constantino legalizó el cristianismo con el Edicto de Milán',
      'El Sacro Imperio Romano Germánico nació en 962',
      'Carlomagno fue coronado emperador en el año 800',
      'Las cruzadas pelearon por el control de Tierra Santa',
      'La Peste Negra mató a un tercio de Europa en el siglo XIV',
      'El Renacimiento revivió el legado clásico en Italia',
      'Galileo defendió el modelo heliocéntrico',
      'Cristóbal Colón murió creyendo haber llegado a Asia',
      'Magallanes inició la primera vuelta al mundo',
      'Hernán Cortés conquistó el Imperio Azteca',
      'Francisco Pizarro derrotó al Imperio Inca',
      'La conquista cobró millones de vidas indígenas',
      'El comercio triangular vinculó América Europa y África',
      'La trata atlántica de esclavos duró cuatro siglos',
      'La Independencia de Estados Unidos fue en 1776',
      'La Declaración de los Derechos del Hombre proviene de Francia',
      'Napoleón Bonaparte dominó Europa entre 1804 y 1815',
      'La Restauración intentó devolver el Antiguo Régimen',
      'Las revoluciones de 1848 sacudieron Europa entera',
      'La Comuna de París duró dos meses en 1871',
      'La unificación de Italia culminó en 1871',
      'Bismarck unificó Alemania bajo Prusia',
      'El Reparto de África ocurrió en la Conferencia de Berlín',
      'La Primera Guerra Mundial comenzó en Sarajevo',
      'Lenin lideró la Revolución de Octubre rusa',
      'La Unión Soviética colapsó en 1991',
      'La Segunda Guerra Mundial empezó con la invasión de Polonia',
      'El Holocausto asesinó a seis millones de judíos',
      'Pearl Harbor llevó a Estados Unidos a la guerra',
      'Las bombas atómicas cayeron en Hiroshima y Nagasaki',
      'La descolonización india fue liderada por Gandhi',
      'Mandela pasó 27 años preso bajo apartheid',
      'La Marcha de Selma marcó los derechos civiles afroamericanos',
      'El Mayo del 68 sacudió universidades francesas',
      'La Primavera de Praga fue aplastada por los tanques soviéticos',
      'El Maoísmo transformó China en el siglo XX',
      'La Revolución Cultural china destruyó patrimonio milenario',
      'Vietnam dividió a Estados Unidos durante una década',
      'El 11 de septiembre cambió la política global',
      'La Primavera Árabe sacudió varios regímenes en 2011',
      'Brexit separó al Reino Unido de la Unión Europea',
      'La pandemia de COVID-19 paralizó el mundo en 2020',
      'La fundación de Roma se data en 753 a.C.',
      'La República Romana duró cinco siglos',
      'Aníbal cruzó los Alpes con elefantes',
      'Espartaco lideró una rebelión de esclavos',
      'Las Termópilas resistieron al ejército persa',
      'Maratón dio nombre a la prueba atlética',
      'La Liga de Delos consolidó la hegemonía ateniense',
      'Alejandro Magno extendió la cultura helenística',
      'Aristóteles fue maestro de Alejandro',
      'Platón fundó la Academia ateniense',
      'Sócrates fue condenado a beber cicuta',
      'La democracia ateniense excluía a esclavos y mujeres',
      'Esparta cultivaba la disciplina militar absoluta',
      'Los hoplitas formaban falanges con escudos solapados',
      'Las olimpiadas antiguas honraban a Zeus',
      'El Imperio Persa fue vencido por Alejandro',
      'Babilonia fue famosa por sus jardines colgantes',
      'Hammurabi redactó uno de los códigos legales más antiguos',
      'Los sumerios inventaron la escritura cuneiforme',
      'Los fenicios crearon el primer alfabeto fonético',
      'Cartago dominaba el Mediterráneo occidental',
      'Las Guerras Púnicas destruyeron Cartago',
      'Constantinopla se llamó Bizancio antes',
      'Estambul es la actual Constantinopla',
      'El Sacro Imperio Romano cayó con Napoleón',
      'La Liga Hanseática controló el comercio del Báltico',
      'Marco Polo describió la China de Kublai Khan',
      'Genghis Khan creó el mayor imperio continental',
      'La Ruta de la Seda conectaba China con Roma',
      'El descubrimiento del Cabo de Buena Esperanza abrió rutas a India',
      'Vasco da Gama llegó a Calicut por el Cabo',
      'La conquista del Imperio Persa duró 13 años',
      'El Reino Visigodo cayó en Guadalete en 711',
      'Los musulmanes dominaron Al-Ándalus durante ocho siglos',
      'La Reconquista terminó con la toma de Granada',
    ],
    queries: [
      'qué eventos marcaron el siglo veinte',
      'civilizaciones antiguas con grandes logros culturales',
      'cómo cayeron los grandes imperios',
    ],
  },
  viajes: {
    phrases: [
      'Kyoto conserva templos y geishas desde el período Heian',
      'El Machu Picchu se accede por el Camino Inca',
      'Petra fue tallada en roca rosa por los nabateos',
      'Santorini ofrece atardeceres sobre la caldera volcánica',
      'Islandia tiene géiseres activos y aurora boreal',
      'Patagonia combina glaciares y estepa salvaje',
      'El Cañón del Colorado se cruza por puentes panorámicos',
      'La Riviera Maya alberga cenotes cristalinos',
      'Tokio mezcla rascacielos y barrios tradicionales',
      'Estambul une Europa y Asia sobre el Bósforo',
      'Marrakech cautiva con el zoco de Jemaa el-Fna',
      'El Camino de Santiago atraviesa toda España',
      'Roma conserva ruinas en cada esquina',
      'Atenas vigila desde la Acrópolis',
      'Praga preserva su centro medieval intacto',
      'Bruselas combina chocolatería y comics',
      'Amsterdam navega por canales arbolados',
      'Berlín muestra arte sobre el antiguo Muro',
      'París pasea por el Sena y sus puentes',
      'Londres ofrece museos gratuitos de clase mundial',
      'Lisboa mira al Tajo desde colinas con tranvías',
      'Madrid madruga en el Rastro los domingos',
      'Barcelona luce arquitectura modernista de Gaudí',
      'Sevilla baila flamenco en Triana',
      'Granada vela bajo la Alhambra al atardecer',
      'Córdoba esconde patios floridos detrás de cada puerta',
      'Bilbao se transformó alrededor del Guggenheim',
      'Valencia inventó la paella sobre el arroz de la Albufera',
      'Mallorca esconde calas turquesas en la sierra de Tramuntana',
      'Tenerife sube al Teide por encima de las nubes',
      'Lanzarote esculpe paisajes volcánicos negros',
      'Gran Canaria mezcla dunas y bosques laurisilva',
      'La Habana ronda con coches americanos de los cincuenta',
      'Buenos Aires baila tango en Caminito',
      'Cusco fue la capital del Imperio Inca',
      'Río de Janeiro abraza Copacabana e Ipanema',
      'Cartagena de Indias guarda murallas coloniales',
      'Bogotá camina por el barrio La Candelaria',
      'Quito asienta su centro histórico sobre los Andes',
      'Galápagos preserva una fauna única',
      'La Antártida solo se visita en verano austral',
      'Nueva Zelanda filma paisajes inolvidables',
      'Australia recorre la Great Ocean Road',
      'Bali calma con templos y arrozales',
      'Tailandia abre paso a islas y templos dorados',
      'Vietnam serpentea por la bahía de Halong',
      'Camboya admira los templos de Angkor al amanecer',
      'Japón florece en hanami durante la primavera',
      'Corea del Sur palpita entre Seúl y el monte Seoraksan',
      'China viaja en tren bala entre Beijing y Shanghai',
      'India sobrecoge con Varanasi sobre el Ganges',
      'Nepal eleva el Everest desde Lukla',
      'Bhután mide la felicidad nacional bruta',
      'Maldivas ofrece bungalows sobre el océano',
      'Sri Lanka cultiva té y guarda elefantes',
      'Madagascar conserva especies endémicas',
      'Tanzania escala el Kilimanjaro',
      'Kenia recorre el Masai Mara',
      'Sudáfrica explora Ciudad del Cabo y los viñedos',
      'Botswana navega el Okavango',
      'Namibia camina sobre las dunas de Sossusvlei',
      'Egipto cruza el Nilo en faluca',
      'Jordania duerme bajo estrellas en Wadi Rum',
      'Israel reza en el Muro de las Lamentaciones',
      'Líbano fusiona costa fenicia y montaña',
      'Irán muestra Isfahán y Persépolis',
      'Uzbekistán recorre Samarcanda',
      'Mongolia cabalga con nómadas en yurta',
      'Siberia atraviesa el Transiberiano',
      'Polonia conserva Cracovia intacta',
      'Hungría se baña en termas en Budapest',
      'Croacia navega entre islas dálmatas',
      'Eslovenia camina por el lago Bled',
      'Eslovaquia esquía en los Tatras',
      'Rumanía visita castillos de Transilvania',
      'Bulgaria recorre monasterios ortodoxos',
      'Grecia salta entre islas del Egeo',
      'Albania sorprende con costa intacta',
      'Montenegro suma fiordos al sur de Europa',
      'Noruega navega los fiordos profundos',
      'Suecia goza de luz interminable en verano',
      'Finlandia respeta sauna y silencio',
      'Dinamarca aventaja en hygge en sus cafés',
      'Escocia recorre las Highlands en tren',
      'Irlanda guarda acantilados de Moher',
      'Gales protege castillos medievales',
      'Cornualles se asoma al océano con faros',
      'Estados Unidos atraviesa la Ruta 66',
      'Canadá viaja en tren entre Toronto y Vancouver',
      'Alaska espera ballenas en Glacier Bay',
      'México combina playas y pirámides',
      'Guatemala asciende volcanes activos',
      'Costa Rica protege selva tropical',
      'Panamá cruza su canal en barco',
      'Colombia respira café en el Eje Cafetero',
      'Venezuela acoge el Salto Ángel',
      'Bolivia atraviesa el Salar de Uyuni',
      'Paraguay recorre las misiones jesuíticas',
      'Uruguay relaja en Colonia del Sacramento',
      'Chile transita desde Atacama a Patagonia',
      'Brasil festeja Carnaval en Salvador',
      'Mar Caribe ofrece arrecifes coloridos',
    ],
    queries: [
      'destinos turísticos imprescindibles para ver paisajes',
      'planificar un viaje cultural por sitios históricos',
      'qué ciudad europea visitar para gastronomía',
    ],
  },
  ciencia: {
    phrases: [
      'La velocidad de la luz es 299792 kilómetros por segundo',
      'La gravedad atrae masas inversamente al cuadrado de la distancia',
      'El ADN codifica instrucciones genéticas en cuatro bases',
      'Las células mitocóndricas producen ATP',
      'La fotosíntesis convierte luz en glucosa',
      'Los átomos consisten en electrones, protones y neutrones',
      'La tabla periódica organiza elementos por número atómico',
      'La entropía mide el desorden de un sistema',
      'El big bang ocurrió hace 13.800 millones de años',
      'Los agujeros negros tienen horizonte de eventos',
      'La materia oscura no emite ni absorbe luz',
      'La relatividad especial unifica espacio y tiempo',
      'La mecánica cuántica describe lo muy pequeño',
      'Los cuásares brillan más que galaxias enteras',
      'La nebulosa del Cangrejo es restos de supernova',
      'Las estrellas fusionan hidrógeno en helio',
      'Las enanas blancas son cadáveres estelares fríos',
      'Los pulsares emiten haces de radio en rotación',
      'El cinturón de Kuiper alberga planetas enanos',
      'Plutón orbita en el cinturón de Kuiper',
      'Marte tiene dos lunas pequeñas, Fobos y Deimos',
      'Júpiter es un gigante gaseoso con gran mancha roja',
      'Saturno luce anillos visibles desde la Tierra',
      'Urano gira inclinado casi sobre su lado',
      'Neptuno tiene vientos supersónicos',
      'Mercurio carece de atmósfera y es escarpado',
      'Venus tiene efecto invernadero extremo',
      'La Luna se aleja de la Tierra unos centímetros por año',
      'Las mareas resultan de la atracción lunar',
      'El campo magnético terrestre nos protege del viento solar',
      'Las auroras polares vienen de partículas solares',
      'La corteza terrestre flota sobre el manto',
      'Las placas tectónicas chocan generando terremotos',
      'Los volcanes liberan magma desde el interior',
      'La litosfera incluye corteza y manto rígido',
      'La estratosfera contiene la capa de ozono',
      'El ozono filtra rayos ultravioleta',
      'El efecto invernadero calienta los planetas',
      'El cambio climático eleva temperaturas medias',
      'El nivel del mar sube por deshielo y expansión térmica',
      'Los corales sufren con aguas más cálidas',
      'La acidificación oceánica daña la vida marina',
      'La biodiversidad sostiene los ecosistemas',
      'Las extinciones masivas reorganizaron la vida cinco veces',
      'Los dinosaurios desaparecieron tras un impacto cósmico',
      'Los mamíferos se diversificaron en el Cenozoico',
      'Los anfibios necesitan agua para reproducirse',
      'Los reptiles regulan temperatura por comportamiento',
      'Las aves descienden de los dinosaurios terópodos',
      'Los peces respiran con branquias',
      'Las plantas vasculares transportan agua por xilema',
      'La fotosíntesis libera oxígeno como subproducto',
      'La respiración celular consume oxígeno y libera CO2',
      'Las mitocondrias tienen ADN propio',
      'Los cloroplastos tienen origen endosimbiótico',
      'Los virus no se consideran vivos por la mayoría',
      'Los retrovirus integran ARN en el ADN huésped',
      'Las bacterias se reproducen por fisión binaria',
      'Los antibióticos atacan procesos bacterianos',
      'Las vacunas entrenan al sistema inmune',
      'Los anticuerpos reconocen antígenos específicos',
      'Las células T destruyen células infectadas',
      'El sistema inmune memoriza patógenos',
      'El cáncer surge de mutaciones acumuladas',
      'La quimioterapia ataca células de división rápida',
      'La inmunoterapia entrena al cuerpo a reconocer tumores',
      'CRISPR edita ADN con precisión sin precedentes',
      'Los telómeros se acortan con cada división celular',
      'Las células madre pueden diferenciarse en muchos tipos',
      'El cerebro humano tiene unos 86 mil millones de neuronas',
      'Las neuronas se comunican por sinapsis químicas',
      'Los neurotransmisores activan canales iónicos',
      'La dopamina regula motivación y movimiento',
      'La serotonina influye en estado de ánimo',
      'El sueño REM consolida memoria',
      'El hipocampo gestiona memoria espacial',
      'La amígdala procesa miedo y emociones',
      'El cerebelo coordina movimiento fino',
      'El sistema nervioso autónomo regula órganos internos',
      'La presión arterial varía con el ciclo cardíaco',
      'Los pulmones intercambian oxígeno y CO2 en alvéolos',
      'Los riñones filtran la sangre y producen orina',
      'El hígado destoxifica y procesa nutrientes',
      'La insulina regula el azúcar en sangre',
      'El glucagón aumenta glucosa cuando baja',
      'Las hormonas viajan por la sangre hasta sus dianas',
      'La pituitaria controla otras glándulas endocrinas',
      'El tiroides regula metabolismo',
      'Las suprarrenales liberan cortisol bajo estrés',
      'Los ovarios producen óvulos y estrógenos',
      'Los testículos producen espermatozoides y testosterona',
      'La meiosis genera células sexuales',
      'La mitosis duplica células somáticas',
      'Los cromosomas humanos son 23 pares',
      'La trisomía 21 causa síndrome de Down',
      'Los genes recesivos se expresan en homocigosis',
      'El alelo dominante enmascara al recesivo',
      'La epigenética modula expresión sin cambiar ADN',
      'Las mutaciones puntuales cambian una sola base',
      'Las inserciones añaden bases al genoma',
      'La selección natural favorece variantes adaptativas',
      'La deriva genética altera frecuencias al azar',
    ],
    queries: [
      'principios fundamentales de la física moderna',
      'cómo funciona el cuerpo humano biológicamente',
      'descubrimientos astronómicos importantes',
    ],
  },
  musica: {
    phrases: [
      'Beethoven compuso nueve sinfonías',
      'La Quinta de Beethoven empieza con un motivo de cuatro notas',
      'Bach escribió las Variaciones Goldberg',
      'Mozart murió antes de terminar su Réquiem',
      'Chopin compuso casi exclusivamente para piano',
      'Wagner revolucionó la ópera con el leitmotiv',
      'Debussy abrió la puerta a la música impresionista',
      'Stravinsky escandalizó París con La Consagración',
      'Schubert murió a los 31 años',
      'Mahler combinó canto y orquesta sinfónica',
      'Brahms perseguía la perfección formal',
      'Tchaikovsky firmó tres ballets célebres',
      'Rachmaninov tenía manos enormes y armonías densas',
      'Shostakovich vivió bajo presión soviética',
      'Sibelius capturó paisajes finlandeses',
      'Ravel orquestó como nadie El Bolero',
      'Bartók recogió música popular húngara',
      'Prokofiev escribió Pedro y el Lobo',
      'Cage exploró el silencio en 4 33',
      'Glass desarrolló el minimalismo repetitivo',
      'Reich inventó el phasing en cintas',
      'Pärt creó la técnica tintinnabuli',
      'Górecki conmovió con su Sinfonía nº 3',
      'Elgar firmó las Pomp and Circumstance',
      'Vaughan Williams celebró música inglesa folclórica',
      'Britten fundó el festival de Aldeburgh',
      'Bernstein dirigió y compuso West Side Story',
      'Gershwin fundió jazz y orquesta sinfónica',
      'Copland evocó las llanuras americanas',
      'Ives mezcló bandas de pueblo y cromatismo',
      'Ellington escribió jazz orquestal sofisticado',
      'Davis revolucionó el jazz cinco veces',
      'Coltrane meditaba en sus solos de saxo',
      'Monk tocaba con armonías excéntricas',
      'Mingus mezclaba blues y experimentación',
      'Parker definió el bebop con su alto saxo',
      'Gillespie llevaba sombrero y mejillas hinchadas',
      'Armstrong popularizó el scat',
      'Fitzgerald improvisaba como un instrumento más',
      'Holiday cantaba con dolor crudo',
      'Vaughan tenía rango operístico',
      'Sinatra dominaba la balada americana',
      'Streisand combina canto y cine',
      'Aretha definió el soul',
      'Brown inventó el funk',
      'Stevie Wonder toca múltiples instrumentos',
      'Marley llevó el reggae al mundo entero',
      'Buena Vista revivió la música cubana',
      'Compay Segundo cantaba con voz grave',
      'El son cubano fundamenta la salsa',
      'La salsa neoyorquina nació en los setenta',
      'Lavoe brillaba con la Fania All Stars',
      'Celia Cruz gritaba azúcar como sello',
      'Tito Puente lideraba con timbales',
      'Buena Onda da nombre a éxitos contemporáneos',
      'El tango porteño habla de nostalgia',
      'Piazzolla actualizó el tango con bandoneón',
      'El flamenco mezcla cante baile y guitarra',
      'Paco de Lucía elevó la guitarra flamenca',
      'Camarón cantó con desgarro absoluto',
      'Sabicas brilló como concertista clásico',
      'El bolero romántico domina la noche latinoamericana',
      'Agustín Lara escribió mil canciones',
      'Armando Manzanero compuso letras tristes',
      'Vicente Fernández cantaba con plumaje',
      'El corrido narra historias revolucionarias',
      'La ranchera lamenta amores perdidos',
      'El mariachi acompaña con trompetas',
      'El son jarocho zapatea sobre tarima',
      'El huapango sube vocalmente al falsete',
      'Pink Floyd construyó conceptos extensos',
      'Led Zeppelin fusionó blues con rock pesado',
      'The Beatles cambiaron música popular para siempre',
      'Queen mezcló ópera y rock',
      'Bowie cambiaba de personaje cada disco',
      'Springsteen cuenta historias de obreros',
      'Joni Mitchell escribió letras como poesía',
      'Dylan recibió el Nobel de literatura',
      'Cohen escribió canciones reflexivas',
      'Joao Gilberto suavizó el ritmo brasileño',
      'Tom Jobim escribió Garota de Ipanema',
      'Caetano y Gil lideraron el tropicalismo',
      'Os Mutantes mezclaron psicodelia',
      'Pernambuco custodia el frevo',
      'Bahía respira axé y candomblé',
      'El forró ronda los acordeones del noreste',
      'El sertanejo invade hoy radios brasileñas',
      'El K-pop explosionó en exportación',
      'El J-pop nutrió generaciones japonesas',
      'El indie español brotó en festivales',
      'Los grupos urbanos dominan plataformas latinas',
      'El reggaetón fusiona dancehall y hip hop',
      'El dembow domina República Dominicana',
      'El trap urbano usa hi-hats rápidos',
      'El drill británico habla con flow grave',
      'El grime nació en Londres',
      'El garage UK trajo voces aceleradas',
      'El house de Chicago revolucionó las pistas',
      'El techno de Detroit nació industrial',
      'El acid house abrió fiestas multitudinarias',
      'El trance eleva con melodías largas',
      'El drum and bass dispara breakbeats',
    ],
    queries: [
      'qué compositores clásicos vale la pena escuchar',
      'géneros musicales que mezclan ritmos del mundo',
      'historia del jazz y el blues',
    ],
  },
  finanzas: {
    phrases: [
      'El interés compuesto reinvierte beneficios sobre principal',
      'La inflación reduce poder adquisitivo del dinero',
      'Los bonos pagan cupones periódicos al tenedor',
      'Las acciones representan participación en una empresa',
      'Los dividendos reparten beneficios a accionistas',
      'Los ETF replican índices con bajos costes',
      'La diversificación reduce riesgo sin sacrificar retorno',
      'El ratio Sharpe ajusta rentabilidad por volatilidad',
      'La curva de tipos refleja expectativas de mercado',
      'Una curva invertida anticipa recesión',
      'La política monetaria mueve los tipos de interés',
      'El BCE controla la política monetaria europea',
      'La Fed marca tipos del dólar estadounidense',
      'La inflación subyacente excluye energía y alimentos',
      'Los CDS aseguran contra default de deuda',
      'El mercado primario emite valores nuevos',
      'El mercado secundario intercambia los ya emitidos',
      'Las IPO sacan empresas a bolsa por primera vez',
      'El short selling vende prestado para recomprar más barato',
      'El margen permite operar con apalancamiento',
      'Una llamada call da derecho a comprar al strike',
      'Una put da derecho a vender al strike',
      'El delta mide sensibilidad al precio subyacente',
      'El gamma mide cambio del delta',
      'Black-Scholes valora opciones europeas',
      'Las volatilidades implícitas se sacan del mercado',
      'El VIX mide volatilidad esperada del S&P 500',
      'Una recesión técnica son dos trimestres negativos',
      'El PIB suma valor añadido en una economía',
      'El PIB per cápita mide riqueza promedio',
      'El IPC mide variación de precios al consumo',
      'El desempleo se mide con encuestas oficiales',
      'La balanza comercial compara exportaciones e importaciones',
      'Un superávit comercial significa exportar más',
      'Un déficit fiscal gasta más que ingresa',
      'La deuda pública acumula déficits',
      'El rescate europeo impuso austeridad griega',
      'Los stress tests evalúan resistencia bancaria',
      'Basilea III refuerza requisitos de capital',
      'El ratio CET1 mide capital de máxima calidad',
      'El LCR exige liquidez para 30 días',
      'Una corrida bancaria drena depósitos',
      'El FDIC asegura depósitos en EE.UU.',
      'El FROB rescató cajas españolas',
      'Lehman Brothers quebró en 2008',
      'La crisis subprime fundió el sistema hipotecario',
      'AIG fue rescatado por el gobierno estadounidense',
      'TARP destinó 700 mil millones a salvar bancos',
      'La gran recesión duró cerca de dos años',
      'Las hipotecas variables suben con el Euribor',
      'El Euribor refleja el coste interbancario',
      'El SOFR sustituyó al LIBOR en dólares',
      'El leasing alquila con opción de compra',
      'El renting paga uso sin opción de compra',
      'Las fintech digitalizan servicios financieros',
      'Revolut nació como cuenta multidivisa',
      'N26 operó como banco digital alemán',
      'Stripe procesa pagos online a empresas',
      'PayPal popularizó pagos peer-to-peer',
      'El Bitcoin nació como respuesta a la crisis de 2008',
      'Ethereum introdujo contratos inteligentes',
      'Las stablecoins anclan valor a una moneda fíat',
      'USDT es la stablecoin con más volumen',
      'Las DeFi reproducen finanzas sin intermediarios',
      'Los DEX cambian activos sin custodia central',
      'Uniswap usa pools de liquidez automáticos',
      'El yield farming busca rentabilidad agresiva',
      'Los staking validan transacciones a cambio de reward',
      'Proof of stake reemplaza minería intensiva',
      'Bitcoin mantiene proof of work',
      'El halving de Bitcoin reduce emisión cada cuatro años',
      'La capitalización es precio multiplicado por circulante',
      'El float ajustado excluye acciones bloqueadas',
      'El P/E ratio compara precio con beneficios',
      'El P/B compara precio con valor en libros',
      'El ROE mide rentabilidad sobre fondos propios',
      'El ROA mide rentabilidad sobre activos',
      'El EBITDA elimina amortizaciones y financiación',
      'Free cash flow muestra caja disponible',
      'WACC mide coste medio del capital',
      'CAPM relaciona riesgo y retorno esperado',
      'El beta mide sensibilidad al mercado',
      'Una cartera 60-40 mezcla acciones y bonos',
      'El rebalanceo restaura proporciones objetivo',
      'Dollar cost averaging suaviza entradas',
      'El value investing busca acciones infravaloradas',
      'Buffett aplica análisis fundamental disciplinado',
      'Graham es el padre del value investing',
      'El growth investing prioriza crecimiento futuro',
      'Los unicornios valen más de mil millones',
      'Los decacornios superan los diez mil millones',
      'El venture capital financia empresas tempranas',
      'Los business angels invierten en pre-seed',
      'El private equity adquiere empresas maduras',
      'Las SPAC fusionan con empresas para sacarlas a bolsa',
      'El M&A combina dos compañías',
      'La due diligence audita antes del cierre',
      'El earnout difiere parte del precio',
      'El locked box fija precio con balance histórico',
      'Las cláusulas tag along protegen al minoritario',
      'Las drag along arrastran al minoritario en venta',
      'El convertible mezcla deuda y opción de equity',
    ],
    queries: [
      'cómo invertir el ahorro de forma diversificada',
      'qué herramientas financieras protegen de la inflación',
      'fundamentos de la economía global y los mercados',
    ],
  },
  salud: {
    phrases: [
      'Caminar una hora diaria reduce riesgo cardiovascular',
      'Dormir siete horas mejora la consolidación de memoria',
      'Comer cinco piezas de fruta y verdura al día previene enfermedades',
      'La dieta mediterránea protege el corazón',
      'El ayuno intermitente regula la insulina',
      'La meditación reduce ansiedad medible',
      'El yoga mejora flexibilidad y equilibrio',
      'El pilates fortalece el core',
      'Correr fortalece el sistema cardiopulmonar',
      'Nadar es ejercicio de bajo impacto articular',
      'Levantar pesas aumenta densidad ósea',
      'Las flexiones trabajan pecho y tríceps',
      'Las sentadillas activan glúteos y cuádriceps',
      'Los burpees combinan fuerza y cardio',
      'El HIIT alterna esfuerzo máximo con descanso',
      'El cardio moderado quema grasa con eficiencia',
      'Hidratarse bien previene calambres musculares',
      'La proteína repara músculos tras entrenar',
      'Los carbohidratos complejos liberan energía sostenida',
      'Las grasas insaturadas protegen el corazón',
      'Las grasas trans elevan el colesterol malo',
      'El omega-3 reduce inflamación crónica',
      'La fibra mejora tránsito intestinal',
      'Los probióticos cuidan microbioma intestinal',
      'Los prebióticos alimentan bacterias buenas',
      'El kimchi y el yogur aportan probióticos',
      'La vitamina D se sintetiza con sol',
      'La vitamina C es antioxidante hidrosoluble',
      'El hierro previene anemia ferropénica',
      'El calcio fortalece huesos',
      'El zinc apoya el sistema inmune',
      'El magnesio relaja músculos',
      'La cafeína estimula el sistema nervioso',
      'El alcohol deteriora hígado a largo plazo',
      'Fumar acorta esperanza de vida',
      'Vapear no es alternativa segura',
      'El estrés crónico daña sistema cardiovascular',
      'Reír reduce hormonas del estrés',
      'Hablar con un amigo alivia carga emocional',
      'La terapia cognitivo-conductual trata ansiedad',
      'La depresión es enfermedad tratable',
      'Los antidepresivos modulan neurotransmisores',
      'El ejercicio físico actúa como antidepresivo',
      'La luz solar regula ritmo circadiano',
      'El insomnio crónico daña sistema metabólico',
      'La apnea del sueño aumenta riesgo cardíaco',
      'CPAP trata apnea moderada y severa',
      'El bruxismo desgasta dientes',
      'El flúor previene caries',
      'Cepillarse dos veces al día protege esmalte',
      'El hilo dental limpia entre dientes',
      'La revisión dental anual detecta caries temprano',
      'El cáncer de piel se previene con protector solar',
      'La luz UV daña ADN cutáneo',
      'La hidratación cutánea ralentiza arrugas',
      'El retinol estimula renovación celular',
      'La crema solar diaria previene manchas',
      'El sueño REM consolida memoria emocional',
      'Las siestas de veinte minutos restauran sin grogginess',
      'El jet lag desincroniza ritmos circadianos',
      'El cambio de hora afecta sueño días después',
      'Una rutina mejora calidad del descanso',
      'La temperatura baja del dormitorio facilita conciliación',
      'Pantallas antes de dormir reducen melatonina',
      'La luz azul retrasa el sueño',
      'El silencio mejora profundidad del descanso',
      'El estrés laboral aumenta riesgo de burnout',
      'Tomar vacaciones recupera salud mental',
      'El mindfulness al respirar calma sistema nervioso',
      'El triángulo respiratorio induce relajación',
      'La coherencia cardiaca sincroniza ritmo y respiración',
      'El biofeedback monitoriza variables fisiológicas',
      'El masaje libera tensión muscular',
      'El stretching diario previene lesiones',
      'El calentamiento prepara para el esfuerzo',
      'El enfriamiento facilita recuperación',
      'La crioterapia reduce inflamación aguda',
      'El sauna mejora circulación',
      'El baño frío estimula sistema nervioso simpático',
      'La hidroterapia alterna calor y frío',
      'El consumo de agua varía con peso y clima',
      'Beber al despertar reactiva metabolismo',
      'El té verde aporta polifenoles',
      'El cacao puro mejora función endotelial',
      'El chocolate negro contiene antioxidantes',
      'Las nueces aportan grasas saludables',
      'Las semillas de chía hidratan al absorber',
      'El aceite de coco tiene grasas saturadas',
      'El aceite de oliva extra virgen reduce inflamación',
      'Las legumbres dan proteína vegetal',
      'El tofu es proteína completa',
      'El tempeh fermentado mejora digestión',
      'Las algas aportan yodo',
      'El pescado azul es rico en omega-3',
      'Las sardinas tienen calcio en las espinas',
      'La caballa concentra vitamina D',
      'El salmón silvestre es preferible al de piscifactoría',
      'Los huevos enteros tienen colina',
      'Los frutos rojos contienen antocianinas',
      'Las cerezas combaten el dolor muscular',
      'El plátano aporta potasio',
      'Las espinacas aportan ácido fólico',
    ],
    queries: [
      'hábitos saludables para mejorar la vida diaria',
      'qué alimentos consumir para sentirme mejor',
      'rutinas de bienestar mental y físico',
    ],
  },
  arte: {
    phrases: [
      'Picasso pintó Guernica en 1937',
      'Las Meninas de Velázquez juegan con perspectivas múltiples',
      'El Bosco pintaba escenas alegóricas detalladas',
      'Goya creó pinturas negras al final de su vida',
      'Miguel Ángel esculpió el David en mármol',
      'Leonardo da Vinci pintó la Mona Lisa al óleo sobre madera',
      'Vermeer captaba luz interior holandesa',
      'Caravaggio inventó el tenebrismo',
      'Rembrandt dominó claroscuros densos',
      'Monet pintó series de la catedral de Rouen',
      'Van Gogh pintó la Noche Estrellada',
      'Cézanne preparó la entrada al cubismo',
      'Matisse coloreaba con planos planos',
      'Dalí desplegaba paisajes oníricos',
      'Magritte cuestionaba representación con palabras',
      'Kahlo pintaba autorretratos intensos',
      'Pollock derramaba pintura sobre lienzo',
      'Rothko buscaba color emoción puro',
      'Bacon distorsionaba rostros con violencia',
      'Hopper congelaba escenas urbanas vacías',
      'Banksy interviene calles con stencils',
      'Basquiat fusionaba grafiti y narrativa',
      'Warhol multiplicaba imágenes de consumo',
      'Hockney pinta piscinas californianas',
      'Hokusai grabó la Gran Ola de Kanagawa',
      'Hiroshige documentó las estaciones del Tokaido',
      'El ukiyo-e influyó al impresionismo francés',
      'El renacimiento florentino redescubrió la perspectiva',
      'Brunelleschi diseñó la cúpula de Florencia',
      'Bramante diseñó el plan inicial de San Pedro',
      'Bernini esculpió la Santa Teresa en éxtasis',
      'Borromini llenó San Carlino de curvas',
      'Gaudí proyectó la Sagrada Familia',
      'Frank Lloyd Wright integró edificios al paisaje',
      'Mies van der Rohe diseñó Barcelona Pavilion',
      'Le Corbusier definió cinco puntos del modernismo',
      'Zaha Hadid creó curvas fluidas en concreto',
      'Tadao Ando usa hormigón texturizado',
      'Calatrava esculpe estructuras blancas',
      'Gehry deforma planos en titanio',
      'Foster diseñó la cúpula del Reichstag',
      'Piano firmó el Centro Pompidou con Rogers',
      'El neoclásico recuperó la simetría griega',
      'El barroco amaba la teatralidad',
      'El rococó suavizó el barroco en pastel',
      'El art nouveau ondulaba líneas naturales',
      'El art déco celebraba geometrías mecánicas',
      'El cubismo descomponía objetos en planos',
      'El surrealismo exploraba el subconsciente',
      'El expresionismo abstracto liberaba gesto',
      'El minimalismo reducía a lo esencial',
      'El conceptualismo prioriza idea sobre objeto',
      'Duchamp expuso un urinario firmado',
      'Yves Klein registró un azul propio',
      'Christo envolvió monumentos en tela',
      'Cristina Iglesias trabaja con agua y bronce',
      'Eduardo Chillida talló hierro y piedra',
      'Jorge Oteiza buscaba la forma vacía',
      'Tàpies incorporaba materia y signos',
      'Miró creaba universo de símbolos infantiles',
      'El graffiti urbano transforma muros grises',
      'La fotografía documental retrata realidades',
      'Henri Cartier-Bresson definió instante decisivo',
      'Robert Capa fotografió la guerra',
      'Vivian Maier guardó miles de negativos',
      'Annie Leibovitz retrata celebridades',
      'Steve McCurry capturó la niña afgana',
      'Sebastião Salgado documenta éxodos humanos',
      'Sally Mann fotografía familia',
      'Cindy Sherman se autorretrata como personajes',
      'Nan Goldin documentó su entorno íntimo',
      'El cine inventó el lenguaje del montaje',
      'Eisenstein teorizó la dialéctica del corte',
      'Kubrick controlaba cada plano milimétricamente',
      'Tarkovsky filmaba largos planos contemplativos',
      'Wes Anderson compone con simetría',
      'Tarantino reordena cronologías',
      'Lynch crea atmósferas oníricas',
      'Almodóvar pinta interiores brillantes',
      'Buñuel cultivó el surrealismo en cine',
      'Bergman filmaba dilemas existenciales',
      'Fellini desbordaba imaginación carnavalesca',
      'Visconti adaptaba novelas con detalle',
      'Antonioni filmaba alienación moderna',
      'Renoir convertía paisajes en cine',
      'Truffaut amaba la nueva ola',
      'Godard rompía gramáticas cinematográficas',
      'Ozu encuadraba a altura del tatami',
      'Mizoguchi seguía con planos secuencia',
      'Kurosawa filmó samuráis épicos',
      'Miyazaki dibuja mundos animados',
      'Pixar revolucionó la animación 3D',
      'Disney clásico dominó la animación tradicional',
      'Studio Ghibli pinta acuarela en cada frame',
      'Aardman moldea plastilina en stop motion',
      'Wes Anderson firmó Isle of Dogs en stop motion',
      'Quay Brothers exploran lo siniestro',
      'Caroline Leaf raya bajo cámara',
      'Norman McLaren animaba directamente sobre película',
    ],
    queries: [
      'movimientos artísticos importantes del siglo veinte',
      'arquitectura icónica de ciudades europeas',
      'pintores que retrataron la luz natural',
    ],
  },
};

export function buildCorpus(): CorpusEntry[] {
  const out: CorpusEntry[] = [];
  for (const [category, data] of Object.entries(CATEGORIES)) {
    for (const phrase of data.phrases) {
      out.push({ text: phrase, category });
    }
  }
  return out;
}

export function buildQueries(): CorpusQuery[] {
  const out: CorpusQuery[] = [];
  for (const [category, data] of Object.entries(CATEGORIES)) {
    for (const q of data.queries) {
      out.push({ query: q, category });
    }
  }
  return out;
}

export function categoryList(): string[] {
  return Object.keys(CATEGORIES);
}
