/**
 * scripts/gen_prompt_catalog.ts — emit the full prompt catalog from the bank.
 *
 * Reads bank/pilot_agentic_v1.jsonl (source of truth) and writes
 * bank/PROMPT_CATALOG.md: for each of the 30 canonical tasks → task_id,
 * category, is_adversarial, and the VERBATIM text of input.prompt.
 *
 * Purpose: the probe corpus must be re-specified to perturb the REAL prompt
 * string (the canonical input has no structured fields — see
 * probes/BINDING_REPORT.md §1). This catalog is that ground truth.
 *
 * Derived by code, never hand-typed, so it cannot drift from the bank.
 * Does NOT modify the canonical bank.
 */

import fs from 'node:fs';
import path from 'node:path';
import { loadBank } from '../src/harness/bank.ts';
import { PATHS } from '../src/core/paths.ts';

const bank = loadBank(PATHS.bank);
if (bank.length !== 30) throw new Error(`expected 30 tasks, got ${bank.length}`);

const sections = bank
  .map((t, i) => {
    const prompt = t.input?.prompt;
    if (typeof prompt !== 'string')
      throw new Error(`task ${t.task_id} has no string input.prompt`);
    return [
      `## ${String(i + 1).padStart(2, '0')}. \`${t.task_id}\``,
      '',
      `- **category:** ${t.category}`,
      `- **is_adversarial:** ${t.adversarial}`,
      `- **grader:** ${t.grader}`,
      '',
      '```text',
      prompt,
      '```',
    ].join('\n');
  })
  .join('\n\n---\n\n');

const advCount = bank.filter((t) => t.adversarial).length;

const md = `# Sello — Canonical Prompt Catalog

> Generated by \`scripts/gen_prompt_catalog.ts\` from \`bank/pilot_agentic_v1.jsonl\`.
> Do NOT hand-edit. Re-run \`npm run gen:catalog\` after any bank change.
>
> The 30 canonical tasks expose input ONLY as \`input.prompt\` (a single string);
> they have no structured fields (CONTRACT §4). This catalog reproduces that
> prompt VERBATIM so probes can be re-specified as perturbations over the real
> prompt text instead of JSONPath over fields that don't exist
> (see \`probes/BINDING_REPORT.md\` §1, §8).

**Totals:** ${bank.length} tasks · ${advCount} adversarial.

---

${sections}
`;

const outPath = path.resolve(path.dirname(PATHS.bank), 'PROMPT_CATALOG.md');
fs.writeFileSync(outPath, md, 'utf-8');
console.log(`✓ wrote ${outPath}`);
console.log(`  ${bank.length} prompts (${advCount} adversarial), all input.prompt verbatim`);
