/**
 * scripts/gen_manifest.ts — emit the canonical ID manifest from the bank.
 *
 * Reads bank/pilot_agentic_v1.jsonl (the source of truth) and writes
 * bank/ID_MANIFEST.md: the 30 real task_ids with category + adversarial mark.
 * Derived by code, never hand-typed, so it cannot drift from the bank.
 */

import fs from 'node:fs';
import path from 'node:path';
import { loadBank } from '../src/harness/bank.ts';
import { PATHS } from '../src/core/paths.ts';

const bank = loadBank(PATHS.bank);
if (bank.length !== 30) throw new Error(`expected 30 tasks, got ${bank.length}`);

const cats = new Map<string, number>();
for (const t of bank) cats.set(t.category, (cats.get(t.category) ?? 0) + 1);
const advIds = bank.filter((t) => t.adversarial).map((t) => t.task_id);

const rows = bank
  .map((t, i) => `| ${String(i + 1).padStart(2, '0')} | \`${t.task_id}\` | ${t.category} | ${t.adversarial ? '**adversarial**' : '—'} | ${t.grader} |`)
  .join('\n');

const md = `# Sello — Canonical Task ID Manifest

> Generated by \`scripts/gen_manifest.ts\` from \`bank/pilot_agentic_v1.jsonl\`.
> Do NOT hand-edit. Re-run \`npm run gen:manifest\` after any bank change.
> This is the frozen ID surface for F0 — expansion candidates and probes target
> these IDs and must not redefine them.

**Totals:** ${bank.length} tasks · 6 categories · ${advIds.length} adversarial.

**Categories:** ${[...cats.entries()].map(([c, n]) => `${c}=${n}`).join(' · ')}

**Adversarial (${advIds.length}):** ${advIds.map((id) => `\`${id}\``).join(', ')}

| # | task_id | category | kind | grader |
|---|---------|----------|------|--------|
${rows}
`;

const outPath = path.resolve(path.dirname(PATHS.bank), 'ID_MANIFEST.md');
fs.writeFileSync(outPath, md, 'utf-8');
console.log(`✓ wrote ${outPath}`);
console.log(`  ${bank.length} tasks, ${cats.size} categories, ${advIds.length} adversarial`);
